FROM node:16.4-slim

WORKDIR /usr/src/server

ENV NODE_ENV=development

# Install system dependencies
# - libssl-dev for Prisma Client
RUN apt-get update -y && \
  apt-get install -y libssl-dev

COPY ./package*.json ./
RUN \
  NODE_ENV=development && \
  npm ci && \
  npm cache clean --force

COPY ./ ./

RUN npm run prisma:generate

CMD [ "npm", "run", "start:dev" ]
